#!/bin/bash

echo "Sourcing ROS"
source /opt/ros/kinetic/setup.bash
echo "Changing directory"
cd ~/Desktop/capture_the_flag/turtlebot_ws
echo "Sourcing the devel"
source devel/setup.bash
echo "Going to run directory"
cd src/turtle_pkg/scripts
echo "Running the server"
rosrun turtle_pkg turtlebot_controller.py
